# Generated by Django 5.2.1 on 2025-07-19 06:00

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdviceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('myuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.myuser')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('sw', 'Swahili')], default='en', max_length=10)),
                ('date_of_birth', models.IntegerField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight_pre_pregnancy', models.FloatField(blank=True, null=True)),
                ('race', models.CharField(blank=True, choices=[('caucasian', 'Caucasian'), ('african', 'African'), ('asian', 'Asian'), ('hispanic', 'Hispanic'), ('mixed', 'Mixed')], max_length=255, null=True)),
                ('country', models.CharField(blank=True, choices=[('nigeria', 'Nigeria'), ('ghana', 'Ghana'), ('other', 'Other')], max_length=255, null=True)),
                ('is_first_pregnancy', models.BooleanField(blank=True, null=True)),
                ('week_of_pregnancy', models.IntegerField(blank=True, null=True)),
                ('tracking_enabled', models.BooleanField(default=False)),
                ('notifications_enabled', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            bases=('api.myuser', models.Model),
        ),
        migrations.CreateModel(
            name='UserMommySymptoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(choices=[('Headache', 'Headache'), ('Nausea', 'Nausea'), ('Fatigue', 'Fatigue'), ('Back Pain', 'Back Pain'), ('Mood Swings', 'Mood Swings')], max_length=255)),
                ('severity', models.IntegerField()),
                ('date_recorded', models.DateField(default=datetime.date.today)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mommy_symptoms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_mommy_symptoms',
                'ordering': ['-date_recorded'],
            },
        ),
        migrations.CreateModel(
            name='UserLifeStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_sleep_hours', models.FloatField(blank=True, null=True)),
                ('work_type', models.CharField(blank=True, choices=[('Desk', 'Desk'), ('Standing', 'Standing'), ('Physical', 'Physical'), ('Care', 'Care'), ('Field', 'Field'), ('Domestic', 'Domestic')], max_length=64, null=True)),
                ('diet_type', models.CharField(blank=True, choices=[('carnivore', 'Carnivore'), ('vegetarian', 'Vegetarian')], max_length=64, null=True)),
                ('cooking_method', models.CharField(blank=True, choices=[('wood', 'Wood'), ('charcoal', 'Charcoal'), ('gas', 'Gas'), ('electric', 'Electric')], max_length=64, null=True)),
                ('activity_duration_minutes', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lifestyle', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBabySymptoms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(choices=[('Kicking', 'Kicking'), ('Hiccups', 'Hiccups'), ('Fetal Movement', 'Fetal Movement'), ('Reduced Movement', 'Reduced Movement')], max_length=255)),
                ('severity', models.IntegerField(blank=True, null=True)),
                ('date_recorded', models.DateField(default=datetime.date.today)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_symptoms',
                'ordering': ['-date_recorded'],
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'movements',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='HealthInsightSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mommy_risk', models.JSONField()),
                ('baby_risk', models.JSONField()),
                ('recommendations', models.JSONField()),
                ('source', models.CharField(default='engine', max_length=32)),
                ('trigger_event', models.CharField(blank=True, max_length=64, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AirExposureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('pm25', models.FloatField(blank=True, null=True)),
                ('pm10', models.FloatField(blank=True, null=True)),
                ('no2', models.FloatField(blank=True, null=True)),
                ('so2', models.FloatField(blank=True, null=True)),
                ('co', models.FloatField(blank=True, null=True)),
                ('o3', models.FloatField(blank=True, null=True)),
                ('aqi', models.IntegerField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('wind_speed', models.FloatField(blank=True, null=True)),
                ('exposure_minutes', models.IntegerField(default=60)),
                ('activity_level', models.CharField(blank=True, max_length=32, null=True)),
                ('indoor', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='air_exposure_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyExposure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregnancy_week', models.PositiveIntegerField()),
                ('exposure_level', models.CharField(choices=[('Clean', 'Clean'), ('Very Good', 'Very Good'), ('Moderate', 'Moderate'), ('Acceptable', 'Acceptable'), ('Unhealthy', 'Unhealthy'), ('High', 'High'), ('Hazardous', 'Hazardous'), ('Extreme', 'Extreme')], max_length=32)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_exposures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pregnancy_week'],
                'unique_together': {('user', 'pregnancy_week')},
            },
        ),
    ]
