# Generated by Django 5.2.1 on 2025-08-02 05:51

from django.db import migrations


def populate_symptom_choices(apps, schema_editor):
    MommySymptom = apps.get_model("api", "MommySymptom")
    BabySymptom = apps.get_model("api", "BabySymptom")

    mommy_symptoms = [
        # yellow
        "fatigue",
        "poor appetite",
        "mild headache",
        # red"
        "headache",
        "swelling",
        "poor sleep",
        "mild shortness of breath",
        # brown
        "persistent headache",
        "dizziness",
        "sleep disturbance",
        "tight chest",
        # black
        "severe fatigue",
        "chest pain",
        "visual changes",
        "shortness of breath",
        # others
        "high blood pressure",
        "upper updominal pain",
        "increase heart rate",
        "fever",
        "vaginal bleeding",
        "increased thirst",
        "increased urination",
        "blurred eyesight",
        "dried mouth",
        "tiredness",
        "no belly growth",
        "poor appetite",
        "updominal pain",
        "lower back pain",
    ]

    baby_symptoms = [
        # yellow
        "reduced movement during sleep",
        # red
        "lower kick count",
        "sluggish response",
        # brown
        "kick count low",
        "reduced rolling",
        "frequent hiccups"
        # black
        "stillness 6hr",
        "fetal distress",
        # others
        "reduced fetal movement",
    ]

    for name in mommy_symptoms:
        MommySymptom.objects.get_or_create(name=name)

    for name in baby_symptoms:
        BabySymptom.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_babysymptom_mommysymptom_and_more"),
    ]

    operations = [
        migrations.RunPython(
            populate_symptom_choices, reverse_code=migrations.RunPython.noop
        ),
    ]
