# Generated by Django 5.2.1 on 2025-07-09 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_healthinsightsnapshot_air_quality_index_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdviceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='trimester',
            new_name='week_of_pregnancy',
        ),
        migrations.CreateModel(
            name='WeeklyExposure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregnancy_week', models.PositiveIntegerField()),
                ('exposure_level', models.CharField(choices=[('Clean', 'Clean'), ('Very Good', 'Very Good'), ('Moderate', 'Moderate'), ('Acceptable', 'Acceptable'), ('Unhealthy', 'Unhealthy'), ('High', 'High'), ('Hazardous', 'Hazardous'), ('Extreme', 'Extreme')], max_length=32)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_exposures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pregnancy_week'],
                'unique_together': {('user', 'pregnancy_week')},
            },
        ),
    ]
