# Generated by Django 5.2.1 on 2025-07-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_advicetemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('sw', 'Swahili')], default='en', max_length=10),
        ),
    ]
