# Generated by Django 5.2.1 on 2025-07-17 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
