# Generated by Django 5.2.1 on 2025-08-02 06:19

from django.db import migrations


def populate_risk_definitions(apps, schema_editor):
    RiskDefinition = apps.get_model("api", "RiskDefinition")

    risk_definitions = [
        {
            "name": "Preeclampsia",
            "description": "",
        },
        {
            "name": "Preterm birth",
            "description": "",
        },
        {
            "name": "GDM",
            "description": "",
        },
        {
            "name": "Low Birth Weight",
            "description": "",
        },
        {
            "name": "Placental abruption",
            "description": "",
        },
    ]

    for definition in risk_definitions:
        RiskDefinition.objects.get_or_create(**definition)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_riskdefinition"),
    ]

    operations = [
        migrations.RunPython(
            populate_risk_definitions, reverse_code=migrations.RunPython.noop
        ),
    ]
