# Generated by Django 5.2.1 on 2025-08-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_populate_risk_definitions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskdefinition',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
