# Generated by Django 5.2.1 on 2025-07-22 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbabysymptoms',
            name='severity',
        ),
        migrations.RemoveField(
            model_name='usermommysymptoms',
            name='severity',
        ),
    ]
