# Generated by Django 5.2.1 on 2025-08-02 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_riskdefinition_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='LifestyleRiskFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplier', models.FloatField()),
                ('condition', models.CharField(max_length=255)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.riskdefinition')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SymptomRiskFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplier', models.FloatField()),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.riskdefinition')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mommysymptom')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserRiskFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplier', models.FloatField()),
                ('condition', models.CharField(max_length=255)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.riskdefinition')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
