# Generated by Django 5.2.1 on 2025-08-02 07:08

from django.db import migrations


def populate_user_risk_factors(apps, schema_editor):
    UserRiskFactor = apps.get_model("api", "UserRiskFactor")
    RiskDefinition = apps.get_model("api", "RiskDefinition")

    preeclampsia_risk = RiskDefinition.objects.get(name="Preeclampsia")
    preterm_birth_risk = RiskDefinition.objects.get(name="Preterm birth")
    gdm_risk = RiskDefinition.objects.get(name="GDM")
    low_birth_weight_risk = RiskDefinition.objects.get(name="Low Birth Weight")

    user_risk_factors = [
        # Preeclampsia risk factors
        {
            "risk": preeclampsia_risk,
            "condition": "bmi>=25",
            "multiplier": 2.8,
        },
        {
            "risk": preeclampsia_risk,
            "condition": "full_year>=35",
            "multiplier": 1.8,
        },
        {
            "risk": preeclampsia_risk,
            "condition": "'race'=='african'",
            "multiplier": 1.6,
        },
        # Preterm birth risk factors
        {
            "risk": preterm_birth_risk,
            "condition": "full_year<=15",
            "multiplier": 1.5,
        },
        {
            "risk": preterm_birth_risk,
            "condition": "full_year>=35 and full_year<=40",
            "multiplier": 1.2,
        },
        {
            "risk": preterm_birth_risk,
            "condition": "full_year>40 and full_year<45",
            "multiplier": 1.4,
        },
        {
            "risk": preterm_birth_risk,
            "condition": "full_year>=45",
            "multiplier": 1.8,
        },
        {
            "risk": preterm_birth_risk,
            "condition": "bmi<=18.5",
            "multiplier": 6.7 / 4.9,
        },
        # GDM risk factors
        {
            "risk": preterm_birth_risk,
            "condition": "bmi>=30",
            "multiplier": 2.5,
        },
        {
            "risk": gdm_risk,
            "condition": "bmi>=30",
            "multiplier": 4.5,
        },
        {
            "risk": gdm_risk,
            "condition": "'race'=='african'",
            "multiplier": 2.0,
        },
        {
            "risk": gdm_risk,
            "condition": "'race'=='asian'",
            "multiplier": 2.0,
        },
        # Low Birth Weight risk factors
        {
            "risk": low_birth_weight_risk,
            "condition": "full_year<20",
            "multiplier": 1.56,
        },
        {
            "risk": low_birth_weight_risk,
            "condition": "bmi<19",
            "multiplier": 1.75,
        },
        {
            "risk": low_birth_weight_risk,
            "condition": "'race'=='african'",
            "multiplier": 2,
        },
    ]
    for risk_factor in user_risk_factors:
        UserRiskFactor.objects.get_or_create(
            risk=risk_factor["risk"],
            condition=risk_factor["condition"],
            multiplier=risk_factor["multiplier"],
        )


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_lifestyleriskfactor_symptomriskfactor_userriskfactor"),
    ]

    operations = [
        migrations.RunPython(
            populate_user_risk_factors, reverse_code=migrations.RunPython.noop
        ),
    ]
