# Generated by Django 5.2.1 on 2025-08-03 07:41

from django.db import migrations


def populate_life_style_risk_factors(apps, schema_editor):
    LifestyleRiskFactor = apps.get_model("api", "LifestyleRiskFactor")
    RiskDefinition = apps.get_model("api", "RiskDefinition")

    preeclampsia_risk = RiskDefinition.objects.get(name="Preeclampsia")
    preterm_birth_risk = RiskDefinition.objects.get(name="Preterm birth")
    gdm_risk = RiskDefinition.objects.get(name="GDM")
    low_birth_weight_risk = RiskDefinition.objects.get(name="Low Birth Weight")

    life_style_risk_factors = [
        # Preeclampsia
        {
            "risk": preeclampsia_risk,
            "condition": "average_sleep_hours<=6",
            "multiplier": 1.4,
        },
        {
            "risk": preeclampsia_risk,
            "condition": "activity_duration_minutes >= 60",
            "multiplier": 0.65,
        },
        {
            "risk": preeclampsia_risk,
            "condition": "work_type==Night Shift",
            "multiplier": 1.75,
        },
        {
            "risk": preeclampsia_risk,
            "condition": "cooking_method==wood or cooking_method==charcoal",
            "multiplier": 2.2,
        },
        # Preterm birth
        {
            "risk": preterm_birth_risk,
            "condition": "average_sleep_hours<=6",
            "multiplier": 1.23,
        },
        {
            "risk": preterm_birth_risk,
            "condition": "work_type==Night Shift",
            "multiplier": 1.21,
        },
        {
            "risk": preterm_birth_risk,
            "condition": "cooking_method==wood or cooking_method==charcoal",
            "multiplier": 1.3,
        },
        # GDM
        {
            "risk": gdm_risk,
            "condition": "average_sleep_hours<=7",
            "multiplier": 1.75,
        },
        {
            "risk": gdm_risk,
            "condition": "work_type==Night Shift",
            "multiplier": 1.75,
        },
        {
            "risk": gdm_risk,
            "condition": "activity_duration_minutes*7 >= 150",
            "multiplier": 0.7,
        },
        {
            "risk": gdm_risk,
            "condition": "diet_type==vegetarian",
            "multiplier": 16.0 / 9.0,
        },
        # Low Birth Weight
        {
            "risk": low_birth_weight_risk,
            "condition": "cooking_method==wood or cooking_method==charcoal",
            "multiplier": 1.5,
        },
    ]


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_populate_user_risk_factors"),
    ]

    operations = []
