# Generated by Django 5.2.1 on 2025-08-06 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_populate_lifestyle_risk_factors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='riskdefinition',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='userlifestyle',
            name='work_type',
            field=models.CharField(blank=True, choices=[('Desk', 'Desk'), ('Standing', 'Standing'), ('Physical', 'Physical'), ('Care', 'Care'), ('Field', 'Field'), ('Domestic', 'Domestic'), ('Night Shift', 'Night Shift')], max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='RiskDefinitionBabySymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baby_symptom_links', to='api.riskdefinition')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.babysymptom')),
            ],
            options={
                'unique_together': {('risk_definition', 'symptom')},
            },
        ),
        migrations.CreateModel(
            name='RiskDefinitionMommySymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mommy_symptom_links', to='api.riskdefinition')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mommysymptom')),
            ],
            options={
                'unique_together': {('risk_definition', 'symptom')},
            },
        ),
    ]
