# Generated by Django 5.2.1 on 2025-08-06 12:33

from django.db import migrations


def populate_risk_definition_symptoms(apps, schema_editor):
    RiskDefinition = apps.get_model("api", "RiskDefinition")
    MommySymptom = apps.get_model("api", "MommySymptom")
    BabySymptom = apps.get_model("api", "BabySymptom")
    RiskDefinitionMommySymptom = apps.get_model("api", "RiskDefinitionMommySymptom")
    RiskDefinitionBabySymptom = apps.get_model("api", "RiskDefinitionBabySymptom")

    # Example: link "Preeclampsia" risk with BMI-related mommy symptom

    preeclampsia = RiskDefinition.objects.get(name="Preeclampsia")
    preterm_birth = RiskDefinition.objects.get(name="Preterm birth")
    gdm = RiskDefinition.objects.get(name="GDM")
    low_birth_weight = RiskDefinition.objects.get(name="Low Birth Weight")
    placental_abruption = RiskDefinition.objects.get(name="Placental abruption")

    high_blood_pressure = MommySymptom.objects.get(name="high blood pressure")
    headache = MommySymptom.objects.get(name="headache")
    upper_updominal_pain = MommySymptom.objects.get(name="upper updominal pain")

    # preeclampsia mommy symptoms
    RiskDefinitionMommySymptom.objects.get_or_create(
        risk_definition=preeclampsia, symptom=high_blood_pressure
    )
    RiskDefinitionMommySymptom.objects.get_or_create(
        risk_definition=preeclampsia, symptom=headache
    )
    RiskDefinitionMommySymptom.objects.get_or_create(
        risk_definition=preeclampsia, symptom=upper_updominal_pain
    )
    # preeclampsia baby symtoms
    reduced_fetal_movement = BabySymptom.objects.get(name="reduced fetal movement")
    RiskDefinitionBabySymptom.objects.get_or_create(
        risk_definition=preeclampsia, symptom=reduced_fetal_movement
    )

    # preterm birth mommy symptoms
    increased_heart_rate = MommySymptom.objects.get(name="increase heart rate")
    RiskDefinitionMommySymptom.objects.get_or_create(
        risk_definition=preterm_birth, symptom=increased_heart_rate
    )
    fever = MommySymptom.objects.get(name="fever")
    RiskDefinitionMommySymptom.objects.get_or_create(
        risk_definition=preterm_birth, symptom=fever
    )
    vaginal_bleeding = MommySymptom.objects.get(name="vaginal bleeding")
    RiskDefinitionMommySymptom.objects.get_or_create(
        risk_definition=preterm_birth, symptom=vaginal_bleeding
    )

    # preterm birth baby symptoms
    RiskDefinitionBabySymptom.objects.get_or_create(
        risk_definition=preterm_birth, symptom=reduced_fetal_movement
    )

    # gdm mommy symptoms
    increased_thirst = MommySymptom.objects.get(name="increased thirst")
    RiskDefinitionMommySymptom.objects.get_or_create(
        risk_definition=gdm, symptom=increased_thirst
    )
    increased_urination = MommySymptom.objects.get(name="increased urination")
    RiskDefinitionMommySymptom.objects.get_or_create(
        risk_definition=gdm, symptom=increased_urination
    )
    blurred_eyesight = MommySymptom.objects.get(name="blurred eyesight")
    RiskDefinitionMommySymptom.objects.get_or_create(
        risk_definition=gdm, symptom=blurred_eyesight
    )
    dried_mouth = MommySymptom.objects.get(name="dried mouth")
    RiskDefinitionMommySymptom.objects.get_or_create(
        risk_definition=gdm, symptom=dried_mouth
    )
    tiredness = MommySymptom.objects.get(name="tiredness")
    RiskDefinitionMommySymptom.objects.get_or_create(
        risk_definition=gdm, symptom=tiredness
    )

    # gdm baby symptoms

    # low birth weight mommy symptoms
    no_belly_growth = MommySymptom.objects.get(name="no belly growth")
    RiskDefinitionMommySymptom.objects.get_or_create(
        risk_definition=low_birth_weight, symptom=no_belly_growth
    )
    dizzyness = MommySymptom.objects.get(name="dizziness")
    RiskDefinitionMommySymptom.objects.get_or_create(
        risk_definition=low_birth_weight, symptom=dizzyness
    )
    poor_appetite = MommySymptom.objects.get(name="poor appetite")
    RiskDefinitionMommySymptom.objects.get_or_create(
        risk_definition=low_birth_weight, symptom=poor_appetite
    )

    # low birth weight baby symptoms
    RiskDefinitionBabySymptom.objects.get_or_create(
        risk_definition=low_birth_weight, symptom=reduced_fetal_movement
    )

    # placental abruption mommy symptoms
    RiskDefinitionMommySymptom.objects.get_or_create(
        risk_definition=placental_abruption, symptom=vaginal_bleeding
    )
    updominal_pain = MommySymptom.objects.get(name="updominal pain")
    RiskDefinitionMommySymptom.objects.get_or_create(
        risk_definition=placental_abruption, symptom=updominal_pain
    )
    lower_back_pain = MommySymptom.objects.get(name="lower back pain")
    RiskDefinitionMommySymptom.objects.get_or_create(
        risk_definition=placental_abruption, symptom=lower_back_pain
    )

    # placental abruption baby symptoms


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_riskdefinition_options_and_more"),
    ]

    operations = [
        migrations.RunPython(
            populate_risk_definition_symptoms, reverse_code=migrations.RunPython.noop
        ),
    ]
