# Generated by Django 5.2.1 on 2025-08-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_populate_risk_definition_symptoms'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskdefinition',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='SymptomRiskFactor',
        ),
    ]
