# Generated by Django 5.2.1 on 2025-08-08 08:22

from django.db import migrations


def set_priorities(apps, schema_editor):
    RiskDefinition = apps.get_model("api", "RiskDefinition")

    preeclampsia_risk = RiskDefinition.objects.get(name="Preeclampsia")
    preeclampsia_risk.priority = 1
    preeclampsia_risk.save()

    preterm_birth_risk = RiskDefinition.objects.get(name="Preterm birth")
    preterm_birth_risk.priority = 2
    preterm_birth_risk.save()

    gdm_risk = RiskDefinition.objects.get(name="GDM")
    gdm_risk.priority = 3
    gdm_risk.save()

    low_birth_weight_risk = RiskDefinition.objects.get(name="Low Birth Weight")
    low_birth_weight_risk.priority = 4
    low_birth_weight_risk.save()

    placental_abruption_risk = RiskDefinition.objects.get(name="Placental abruption")
    placental_abruption_risk.priority = 5
    placental_abruption_risk.save()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_riskdefinition_priority_delete_symptomriskfactor"),
    ]

    operations = [
        migrations.RunPython(set_priorities, migrations.RunPython.noop),
    ]
