# Generated by Django 5.2.1 on 2025-08-16 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_populate_risk_definitions_prioriies'),
    ]

    operations = [
        migrations.CreateModel(
            name='AQRiskFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplier', models.FloatField()),
                ('condition', models.CharField(max_length=255)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.riskdefinition')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
