# Generated by Django 5.2.1 on 2025-08-22 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_exposure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exposure',
            old_name='exposure',
            new_name='exposure_level',
        ),
    ]
