# Generated by Django 5.2.1 on 2025-08-22 08:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_exposure_exposure_exposure_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exposure',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='exposure',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='exposure',
            name='timestamp',
            field=models.DateField(default=django.utils.timezone.localdate, editable=False),
        ),
        migrations.AlterField(
            model_name='exposure',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exposures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='exposure',
            index=models.Index(fields=['user', 'timestamp'], name='api_exposur_user_id_8db16f_idx'),
        ),
        migrations.AddConstraint(
            model_name='exposure',
            constraint=models.UniqueConstraint(fields=('user', 'timestamp'), name='uniq_exposure_user_date'),
        ),
    ]
