# Generated by Django 5.2.1 on 2025-08-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_exposure_options_exposure_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exposure',
            name='pollutants',
            field=models.JSONField(default=dict),
        ),
    ]
