# Generated by Django 5.2.1 on 2025-09-01 12:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_exposure_pollutants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbabysymptoms',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usermommysymptoms',
            options={},
        ),
        migrations.RemoveField(
            model_name='userbabysymptoms',
            name='date_recorded',
        ),
        migrations.RemoveField(
            model_name='usermommysymptoms',
            name='date_recorded',
        ),
        migrations.AddField(
            model_name='userbabysymptoms',
            name='recorded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usermommysymptoms',
            name='recorded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userbabysymptoms',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usermommysymptoms',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='userbabysymptoms',
            table='user_baby_symptoms',
        ),
    ]
