# Generated by Django 5.2.1 on 2025-09-01 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_exposure_pollutants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbabysymptoms',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usermommysymptoms',
            options={},
        ),
        migrations.AlterField(
            model_name='userbabysymptoms',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usermommysymptoms',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='userbabysymptoms',
            table='user__baby_symptoms',
        ),
    ]
