# Generated by Django 5.2.1 on 2025-09-01 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_userbabysymptoms_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userbabysymptoms',
            table='user_baby_symptoms',
        ),
    ]
