# Generated by Django 5.2.1 on 2025-09-08 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_userbabysymptoms_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbabysymptoms',
            options={'ordering': ['-recorded_at']},
        ),
        migrations.AlterModelOptions(
            name='usermommysymptoms',
            options={'ordering': ['-recorded_at']},
        ),
        migrations.AlterField(
            model_name='airexposurelog',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='userbabysymptoms',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usermommysymptoms',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mommy_symptoms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='userbabysymptoms',
            table='user_symptoms',
        ),
    ]
