# Generated by Django 5.2.1 on 2025-09-08 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_userbabysymptoms_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='babysymptom',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mommysymptom',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userbabysymptoms',
            options={},
        ),
        migrations.AlterModelOptions(
            name='usermommysymptoms',
            options={},
        ),
        migrations.AlterField(
            model_name='userbabysymptoms',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usermommysymptoms',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='babysymptom',
            table='baby_symptoms',
        ),
        migrations.AlterModelTable(
            name='mommysymptom',
            table='mommy_symptoms',
        ),
        migrations.AlterModelTable(
            name='userbabysymptoms',
            table='user_baby_symptoms',
        ),
    ]
