# Generated by Django 5.2.1 on 2025-09-01 09:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_userbabysymptoms_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='babysymptom',
            options={},
        ),
        migrations.RemoveField(
            model_name='babysymptom',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userbabysymptoms',
            name='date_recorded',
        ),
        migrations.RemoveField(
            model_name='usermommysymptoms',
            name='date_recorded',
        ),
        migrations.AddField(
            model_name='userbabysymptoms',
            name='recorded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usermommysymptoms',
            name='recorded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
