# Generated by Django 5.2.1 on 2025-09-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_babysymptom_options_alter_mommysymptom_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exposure',
            name='risks',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
