# Generated by Django 5.2.1 on 2025-09-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_exposure_risks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthinsightsnapshot',
            name='baby_risk',
        ),
        migrations.RemoveField(
            model_name='healthinsightsnapshot',
            name='mommy_risk',
        ),
        migrations.AddField(
            model_name='healthinsightsnapshot',
            name='engine_version',
            field=models.CharField(default='receng-mvp-0.1', max_length=32),
        ),
        migrations.AlterField(
            model_name='healthinsightsnapshot',
            name='recommendations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddIndex(
            model_name='healthinsightsnapshot',
            index=models.Index(fields=['user', '-created_at'], name='api_healthi_user_id_4305fd_idx'),
        ),
    ]
