# Generated by Django 5.2.1 on 2025-09-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_healthinsightsnapshot_baby_risk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, choices=[('NG', 'Nigeria'), ('GH', 'Ghana'), ('KE', 'Kenya'), ('other', 'Other')], max_length=255, null=True),
        ),
    ]
