# Generated by Django 5.2.1 on 2025-09-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='airexposurelog',
            name='pressure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airexposurelog',
            name='uvi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airexposurelog',
            name='uvi_level',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
