# Generated by Django 5.2.1 on 2025-10-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_user_auth_provider_user_avatar_url_user_google_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('sw', 'Swahili'), ('pl', 'Polish')], default='en', max_length=10),
        ),
        migrations.CreateModel(
            name='GuidelineLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pollutant', models.CharField(choices=[('pm25', 'PM2.5'), ('pm10', 'PM10'), ('no2', 'NO₂'), ('o3', 'O₃'), ('so2', 'SO₂'), ('co', 'CO')], db_index=True, max_length=10)),
                ('avg_period', models.CharField(choices=[('24h', '24h mean'), ('8h', '8h mean'), ('1h', '1h mean'), ('annual', 'annual')], db_index=True, max_length=10)),
                ('value', models.FloatField(help_text='Limit value in the specified unit')),
                ('unit', models.CharField(default='µg/m³', help_text='e.g. µg/m³ or mg/m³', max_length=16)),
                ('source', models.CharField(default='WHO', max_length=64)),
                ('version', models.CharField(db_index=True, default='AQG 2021', max_length=64)),
                ('valid_from', models.DateField(blank=True, default=None, null=True)),
                ('valid_to', models.DateField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'guideline_limits',
                'ordering': ['pollutant', 'avg_period', '-is_active', 'version', '-created_at'],
                'unique_together': {('pollutant', 'avg_period', 'version', 'source')},
            },
        ),
    ]
