# Generated by Django 5.2.1 on 2025-10-16 12:30

from django.db import migrations

from django.db import migrations, models
import django.utils.timezone


def seed_who_aqg_2021(apps, schema_editor):
    GuidelineLimit = apps.get_model("api", "GuidelineLimit")

    defaults = [
        # pollutant, avg_period, value, unit
        ("pm25", "24h", 15.0, "µg/m³"),
        ("pm10", "24h", 45.0, "µg/m³"),
        ("no2", "24h", 25.0, "µg/m³"),
        ("o3", "8h", 100.0, "µg/m³"),
        ("so2", "24h", 40.0, "µg/m³"),
        ("co", "24h", 4.0, "mg/m³"),
    ]

    for pol, period, val, unit in defaults:
        GuidelineLimit.objects.get_or_create(
            pollutant=pol,
            avg_period=period,
            version="AQG 2021",
            source="WHO",
            defaults={
                "value": val,
                "unit": unit,
                "is_active": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_alter_user_language_guidelinelimit"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuidelineLimit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pollutant",
                    models.CharField(
                        choices=[
                            ("pm25", "PM2.5"),
                            ("pm10", "PM10"),
                            ("no2", "NO₂"),
                            ("o3", "O₃"),
                            ("so2", "SO₂"),
                            ("co", "CO"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "avg_period",
                    models.CharField(
                        choices=[
                            ("24h", "24h mean"),
                            ("8h", "8h mean"),
                            ("1h", "1h mean"),
                            ("annual", "annual"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "value",
                    models.FloatField(help_text="Limit value in the specified unit"),
                ),
                (
                    "unit",
                    models.CharField(
                        default="µg/m³", help_text="e.g. µg/m³ or mg/m³", max_length=16
                    ),
                ),
                ("source", models.CharField(default="WHO", max_length=64)),
                (
                    "version",
                    models.CharField(db_index=True, default="AQG 2021", max_length=64),
                ),
                ("valid_from", models.DateField(blank=True, null=True, default=None)),
                ("valid_to", models.DateField(blank=True, null=True, default=None)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "guideline_limits",
                "ordering": [
                    "pollutant",
                    "avg_period",
                    "-is_active",
                    "version",
                    "-created_at",
                ],
                "unique_together": {("pollutant", "avg_period", "version", "source")},
            },
        ),
        migrations.RunPython(seed_who_aqg_2021, migrations.RunPython.noop),
    ]


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_alter_user_language_guidelinelimit"),
    ]

    operations = []
