# Generated by Django 5.2.1 on 2025-10-16 12:30

from django.db import migrations

from django.db import migrations, models
import django.utils.timezone


def seed_who_aqg_2021(apps, schema_editor):
    GuidelineLimit = apps.get_model("api", "GuidelineLimit")

    defaults = [
        # pollutant, avg_period, value, unit
        ("pm25", "24h", 15.0, "µg/m³"),
        ("pm10", "24h", 45.0, "µg/m³"),
        ("no2", "24h", 25.0, "µg/m³"),
        ("o3", "8h", 100.0, "µg/m³"),
        ("so2", "24h", 40.0, "µg/m³"),
        ("co", "24h", 4.0, "mg/m³"),
    ]

    for pol, period, val, unit in defaults:
        GuidelineLimit.objects.get_or_create(
            pollutant=pol,
            avg_period=period,
            version="AQG 2021",
            source="WHO",
            defaults={
                "value": val,
                "unit": unit,
                "is_active": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_alter_user_language_guidelinelimit"),
    ]

    operations = [
        migrations.RunPython(seed_who_aqg_2021, migrations.RunPython.noop),
    ]
