# Generated by Django 5.2.1 on 2026-02-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_populate_quideline_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='consent_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='prefered_share_channel',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userlifestyle',
            name='commute_mode',
            field=models.CharField(blank=True, choices=[('walk', 'Walk'), ('matatu-bus', 'Matatu/Bus'), ('bike', 'Bike'), ('car', 'Car'), ('mixed', 'Mixed')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='userlifestyle',
            name='cooking_venue',
            field=models.CharField(blank=True, choices=[('indoor', 'Indoor'), ('veranda', 'Veranda'), ('outdoor', 'Outdoor')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='userlifestyle',
            name='hydration_target_ml_per_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlifestyle',
            name='rest_microbreak_preference',
            field=models.CharField(blank=True, choices=[('5min', '5 min'), ('10min', '10 min'), ('15min', '15 min')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='userlifestyle',
            name='sleep_target_window',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='userlifestyle',
            name='standing_hours_per_day',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlifestyle',
            name='supplement_preferences',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userlifestyle',
            name='ventilation_level',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='userlifestyle',
            name='work_schedule_pattern',
            field=models.CharField(blank=True, choices=[('day', 'Day'), ('evening', 'Evening'), ('irregular', 'Irregular')], max_length=60, null=True),
        ),
    ]
