# Generated by Django 5.2.1 on 2026-02-20 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_user_consent_user_consent_accepted_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='prefered_share_channel',
            new_name='preferred_share_channel',
        ),
    ]
