# Generated by Django 5.2.1 on 2026-02-21 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_rename_prefered_share_channel_user_preferred_share_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(max_length=128)),
                ('rule_version', models.PositiveIntegerField(default=1)),
                ('dimension', models.CharField(choices=[('diet', 'Diet'), ('activity', 'Activity'), ('behavior', 'Behavior')], max_length=16)),
                ('status', models.CharField(choices=[('done', 'Done'), ('skipped', 'Skipped'), ('dismissed', 'Dismissed')], default='done', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='api.healthinsightsnapshot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recommendation_completions',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', '-updated_at'], name='recommendat_user_id_70ab79_idx'), models.Index(fields=['snapshot', 'rule_id', 'rule_version'], name='recommendat_snapsho_908904_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'snapshot', 'rule_id', 'rule_version', 'dimension'), name='uniq_user_snapshot_rule_dimension')],
            },
        ),
    ]
