# Generated by Django 5.2.1 on 2026-02-28 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_recommendationcompletion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyExposure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('exposure_level', models.CharField(choices=[('Clean', 'Clean'), ('Very Good', 'Very Good'), ('Moderate', 'Moderate'), ('Acceptable', 'Acceptable'), ('Unhealthy', 'Unhealthy'), ('High', 'High'), ('Hazardous', 'Hazardous'), ('Extreme', 'Extreme')], max_length=32)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_exposures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
