# Generated by Django 5.2.1 on 2026-02-28 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_dailyexposure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wellbeing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('mood', 'Mood (chips)'), ('feeling', 'Feeling (chips)'), ('water_goal', 'Water goal/setting')], max_length=32)),
                ('code', models.SlugField(blank=True, max_length=64, null=True, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('number_value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, default='fl_oz', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['kind', 'sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='UserWellbeingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('water_amount', models.FloatField(default=0)),
                ('water_unit', models.CharField(default='fl_oz', max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wellbeing_logs', to=settings.AUTH_USER_MODEL)),
                ('feelings', models.ManyToManyField(blank=True, related_name='feeling_logs', to='api.wellbeing')),
                ('moods', models.ManyToManyField(blank=True, related_name='mood_logs', to='api.wellbeing')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
