# Generated by Django 5.2.1 on 2026-02-28 10:56

from django.db import migrations


def seed_wellbeing(apps, schema_editor):
    Wellbeing = apps.get_model("api", "Wellbeing")

    # 1) Water goal (one row)
    # If exists — update to defaults; if not — create.
    water_defaults = {
        "number_value": 72,
        "unit": "fl_oz",
        "is_active": True,
        "sort_order": 0,
    }
    water_obj = Wellbeing.objects.filter(kind="water_goal").order_by("id").first()
    if water_obj:
        for k, v in water_defaults.items():
            setattr(water_obj, k, v)
        water_obj.save()
    else:
        Wellbeing.objects.create(kind="water_goal", **water_defaults)

    # 2) Mood chips
    moods = [
        {"code": "feel_sick", "title": "Feel sick", "sort_order": 10},
        {"code": "distressed", "title": "Distressed", "sort_order": 20},
        {"code": "nervous", "title": "Nervous", "sort_order": 30},
        {"code": "nauseous", "title": "Nauseous", "sort_order": 40},
    ]
    for item in moods:
        Wellbeing.objects.update_or_create(
            kind="mood",
            code=item["code"],
            defaults={
                "title": item["title"],
                "sort_order": item["sort_order"],
                "is_active": True,
                "number_value": None,
                "unit": "",
            },
        )

    # 3) Feeling chips (your бывший "Symptoms")
    feelings = [
        {"code": "everything_is_fine", "title": "Everything is fine", "sort_order": 10},
        {"code": "poor_sleep", "title": "Poor Sleep", "sort_order": 20},
        {"code": "headache", "title": "Headache", "sort_order": 30},
    ]
    for item in feelings:
        Wellbeing.objects.update_or_create(
            kind="feeling",
            code=item["code"],
            defaults={
                "title": item["title"],
                "sort_order": item["sort_order"],
                "is_active": True,
                "number_value": None,
                "unit": "",
            },
        )


def unseed_wellbeing(apps, schema_editor):
    Wellbeing = apps.get_model("api", "Wellbeing")
    Wellbeing.objects.filter(
        code__in=[
            "feel_sick",
            "distressed",
            "nervous",
            "nauseous",
            "everything_is_fine",
            "poor_sleep",
            "headache",
        ]
    ).delete()
    # water_goal удалять не будем (обычно это “настройка”), но если хочешь — могу включить.


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_wellbeing_userwellbeinglog"),
    ]

    operations = [
        migrations.RunPython(seed_wellbeing, unseed_wellbeing),
    ]
