# Generated by Django 5.2.1 on 2026-04-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_populate_wellbeing'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pregnancy_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
