# Generated by Django 5.2.1 on 2026-06-22 07:59

from django.db import migrations, models


def populate_daily_task_categories(apps, schema_editor):
    DailyTask = apps.get_model("api", "DailyTask")
    categories_by_code = {
        "drink_water": "diet",
        "morning_walk": "activity",
        "cooking_smoke": "behavior",
    }
    for code, category in categories_by_code.items():
        DailyTask.objects.filter(code=code).update(category=category)


def reset_daily_task_categories(apps, schema_editor):
    DailyTask = apps.get_model("api", "DailyTask")
    DailyTask.objects.update(category="behavior")


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_seed_risk_factor_matrix'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytask',
            name='category',
            field=models.CharField(choices=[('diet', 'Diet'), ('activity', 'Activity'), ('behavior', 'Behavior'), ('mental', 'Mental')], db_index=True, default='behavior', max_length=16),
        ),
        migrations.RunPython(
            populate_daily_task_categories,
            reset_daily_task_categories,
        ),
    ]
