# Generated by Django 5.2.1 on 2026-07-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_dailytask_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification_window_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_window_to',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pregnancy_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='userlifestyle',
            name='area',
            field=models.CharField(blank=True, choices=[('urban', 'Urban'), ('peri_urban', 'Peri-Urban'), ('rural', 'Rural')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='userlifestyle',
            name='time_of_day',
            field=models.CharField(blank=True, choices=[('morning_hours', 'Morning hours'), ('midday_or_afternoon', 'Midday or afternoon'), ('evening', 'Evening'), ('changes_day_to_day', 'It changes day to day')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='userlifestyle',
            name='time_spent',
            field=models.CharField(blank=True, choices=[('mostly_indoors', 'Mostly indoors'), ('mostly_outdoors', 'Mostly outdoors'), ('both_equally', 'Both equally')], max_length=32, null=True),
        ),
    ]
