# Generated by Django 5.2.1 on 2026-07-05 13:30

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_user_notification_window_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.user_avatar_upload_to),
        ),
    ]
