# Generated by Django 5.2.1 on 2026-09-05 09:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_symptom_checklist_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_date', models.DateField()),
                ('timezone', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-local_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stable_key', models.CharField(max_length=255)),
                ('domain', models.CharField(choices=[('nutrition', 'Nutrition'), ('activity', 'Activity'), ('behavior', 'Behavior'), ('mental', 'Mental'), ('service', 'Service')], max_length=16)),
                ('role', models.CharField(choices=[('primary', 'Primary'), ('additional', 'Additional'), ('support', 'Support')], max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('timing', models.CharField(blank=True, max_length=128, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('context', models.CharField(blank=True, max_length=255, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('source_type', models.CharField(choices=[('recommendation', 'Recommendation'), ('task', 'Task')], max_length=16)),
                ('source_task_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('source_snapshot_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('source_rule_id', models.CharField(blank=True, max_length=128, null=True)),
                ('source_rule_version', models.PositiveIntegerField(blank=True, null=True)),
                ('source_dimension', models.CharField(blank=True, choices=[('diet', 'Diet'), ('activity', 'Activity'), ('behavior', 'Behavior')], max_length=16, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='api.dailyplan')),
            ],
            options={
                'ordering': ['sort_order', 'stable_key'],
            },
        ),
        migrations.AddIndex(
            model_name='dailyplan',
            index=models.Index(fields=['user', 'local_date'], name='api_dailypl_user_id_f324e8_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailyplan',
            constraint=models.UniqueConstraint(fields=('user', 'local_date'), name='uniq_daily_plan_user_local_date'),
        ),
        migrations.AddIndex(
            model_name='dailyaction',
            index=models.Index(fields=['plan', 'role', 'sort_order'], name='api_dailyac_plan_id_36fdcb_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyaction',
            index=models.Index(fields=['source_snapshot_id', 'source_rule_id'], name='api_dailyac_source__e154d9_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailyaction',
            constraint=models.UniqueConstraint(fields=('plan', 'stable_key'), name='uniq_daily_action_plan_stable_key'),
        ),
        migrations.AddConstraint(
            model_name='dailyaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_dimension__isnull', True), ('source_rule_id__isnull', True), ('source_rule_version__isnull', True), ('source_snapshot_id__isnull', True), ('source_task_id__isnull', False), ('source_type', 'task')), models.Q(('source_dimension__isnull', False), ('source_rule_id__isnull', False), ('source_rule_version__isnull', False), ('source_snapshot_id__isnull', False), ('source_task_id__isnull', True), ('source_type', 'recommendation')), _connector='OR'), name='valid_daily_action_source'),
        ),
        migrations.AddConstraint(
            model_name='dailyaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('domain', 'service'), ('role', 'support')), models.Q(('role__in', ['primary', 'additional']), models.Q(('domain', 'service'), _negated=True)), _connector='OR'), name='valid_daily_action_role_domain'),
        ),
    ]
