# Generated by Django 5.2.1 on 2026-09-30 04:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_user_email_verification_pending'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('action', models.CharField(blank=True, max_length=255)),
                ('method', models.CharField(max_length=16)),
                ('path', models.TextField()),
                ('status_code', models.PositiveSmallIntegerField()),
                ('duration_ms', models.PositiveIntegerField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_headers', models.JSONField(blank=True, default=dict)),
                ('query_params', models.JSONField(blank=True, default=dict)),
                ('request_body', models.JSONField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('error_type', models.CharField(blank=True, max_length=255)),
                ('traceback', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp', '-id'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='api_auditlo_user_id_6b4e90_idx'), models.Index(fields=['action', '-timestamp'], name='api_auditlo_action_e9644f_idx'), models.Index(fields=['status_code', '-timestamp'], name='api_auditlo_status__fa0208_idx')],
            },
        ),
    ]
