# Generated by Django 5.2.1 on 2026-05-28 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended')], default='draft', max_length=16)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AdPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AdCreative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(choices=[('native_card', 'Native card'), ('banner', 'Banner')], default='native_card', max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads/')),
                ('cta_text', models.CharField(blank=True, default='', max_length=64)),
                ('target_url', models.URLField()),
                ('sponsor_label', models.CharField(default='Sponsored', max_length=64)),
                ('locale', models.CharField(blank=True, default='', max_length=10)),
                ('country', models.CharField(blank=True, default='', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatives', to='ads.adcampaign')),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creatives', to='ads.adplacement')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AdClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField()),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ads.adcampaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('creative', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ads.adcreative')),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ads.adplacement')),
            ],
            options={
                'ordering': ['-clicked_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='adcampaign',
            name='advertiser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='ads.advertiser'),
        ),
        migrations.CreateModel(
            name='AdImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField()),
                ('shown_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ads.adcampaign')),
                ('creative', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ads.adcreative')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ads.adplacement')),
            ],
            options={
                'ordering': ['-shown_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['user', 'request_id'], name='ads_adimpre_user_id_d97bbb_idx'), models.Index(fields=['creative', 'request_id'], name='ads_adimpre_creativ_348638_idx'), models.Index(fields=['campaign', '-shown_at'], name='ads_adimpre_campaig_146867_idx'), models.Index(fields=['placement', '-shown_at'], name='ads_adimpre_placeme_02fce4_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='adcreative',
            index=models.Index(fields=['is_active', 'locale', 'country'], name='ads_adcreat_is_acti_e3e320_idx'),
        ),
        migrations.AddIndex(
            model_name='adcreative',
            index=models.Index(fields=['placement', 'is_active'], name='ads_adcreat_placeme_5ee4c0_idx'),
        ),
        migrations.AddIndex(
            model_name='adclick',
            index=models.Index(fields=['user', 'request_id'], name='ads_adclick_user_id_849205_idx'),
        ),
        migrations.AddIndex(
            model_name='adclick',
            index=models.Index(fields=['creative', 'request_id'], name='ads_adclick_creativ_983cec_idx'),
        ),
        migrations.AddIndex(
            model_name='adclick',
            index=models.Index(fields=['campaign', '-clicked_at'], name='ads_adclick_campaig_ea2bf2_idx'),
        ),
        migrations.AddIndex(
            model_name='adclick',
            index=models.Index(fields=['placement', '-clicked_at'], name='ads_adclick_placeme_9c078d_idx'),
        ),
        migrations.AddIndex(
            model_name='adcampaign',
            index=models.Index(fields=['status', 'starts_at', 'ends_at'], name='ads_adcampa_status_71feaf_idx'),
        ),
    ]
