"""
Django settings for agent_api project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import json
import os

from datetime import timedelta
from pathlib import Path
from dotenv import load_dotenv

from pathlib import Path

import logging

import firebase_admin
from firebase_admin import credentials

logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger(__name__)

settings_path = Path(__file__).resolve()
logger.info(f"Settings file path: {settings_path}")

intermediate_base_dir = settings_path.parent.parent
logger.info(f"Intermediate BASE_DIR: {intermediate_base_dir}")

load_dotenv(dotenv_path=intermediate_base_dir / ".env")

DJANGO_ENV = os.getenv("DJANGO_ENV", "development")
print(f"DJANGO_ENV: {DJANGO_ENV}")
OWM_API_KEY = os.getenv("OWM_API_KEY")
print(f"OWM_API_KEY is set: {OWM_API_KEY is not None}")

MOVEMENT_H3_RESOLUTION = int(os.getenv("MOVEMENT_H3_RESOLUTION", "8"))
MOVEMENT_COORDINATE_ACTIVE_KEY_VERSION = int(
    os.getenv("MOVEMENT_COORDINATE_ACTIVE_KEY_VERSION", "1")
)

_coordinate_keys_raw = os.getenv("MOVEMENT_COORDINATE_KEYS", "{}")
try:
    _coordinate_keys = json.loads(_coordinate_keys_raw)
    if not isinstance(_coordinate_keys, dict):
        raise ValueError("MOVEMENT_COORDINATE_KEYS must be a JSON object")
    MOVEMENT_COORDINATE_KEYS = {
        int(version): encoded_key for version, encoded_key in _coordinate_keys.items()
    }
except (TypeError, ValueError, json.JSONDecodeError) as exc:
    raise ValueError("MOVEMENT_COORDINATE_KEYS must be a valid JSON object") from exc


if DJANGO_ENV in {"staging", "production"}:
    BASE_DIR = settings_path.parent
    TEMPLATE_DIR = settings_path.parent.parent / "templates"
else:
    BASE_DIR = settings_path.parent.parent
    TEMPLATE_DIR = BASE_DIR / "templates"
logger.info(f"BASE_DIR: {BASE_DIR}, TEMPLATE_DIR: {TEMPLATE_DIR}")


load_dotenv(dotenv_path=BASE_DIR / ".env")

FIREBASE_CREDENTIALS = os.getenv("FIREBASE_CREDENTIALS")
if FIREBASE_CREDENTIALS and not firebase_admin._apps:
    cred = credentials.Certificate(FIREBASE_CREDENTIALS)
    firebase_admin.initialize_app(cred)


print(f"BASE_DIR: {BASE_DIR}")
DEBUG = os.getenv("DEBUG", "True").lower() in ("true", "1", "yes")
SECRET_KEY = os.getenv(
    "SECRET_KEY", "django-insecure-p9d!a)b726f1^*3h=h+^xkz)a@x7*(%)#11_0qsl#oy^vsb$f@"
)
# SECURITY WARNING: don't run with debug turned on in production!

ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "127.0.0.1").split(",")

REGISTRATION_API_KEY = os.getenv("REGISTRATION_API_KEY")

HEALTH_INSIGHT_SNAPSHOT_FRESH_HOURS = int(
    os.getenv("HEALTH_INSIGHT_SNAPSHOT_FRESH_HOURS", "6")
)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = "django-insecure-p9d!a)b726f1^*3h=h+^xkz)a@x7*(%)#11_0qsl#oy^vsb$f@"

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

AUTH_USER_MODEL = "api.User"

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # our
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    # our apps
    "api",
    "demo_interface",
    "recommendations",
    # third-party apps
    "drf_spectacular",
    "drf_spectacular_sidecar",
    #
    "debug_toolbar",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # standard middleware
    "django.contrib.sessions.middleware.SessionMiddleware",
    # my custom middleware
    "api.middleware.AdminLoginDebugMiddleware",
    #
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # third-party middleware
    "debug_toolbar.middleware.DebugToolbarMiddleware",
]


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [TEMPLATE_DIR],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

ROOT_URLCONF = "agent_api.urls"

WSGI_APPLICATION = "agent_api.wsgi.application"
ASGI_APPLICATION = "agent_api.asgi.application"  # required for uvicorn


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if not DJANGO_ENV in {"production", "staging"}:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("DB_NAME"),
            "USER": os.getenv("DB_USER"),
            "PASSWORD": os.getenv("DB_PASSWORD"),
            "HOST": os.getenv("DB_HOST", "localhost"),
            "PORT": os.getenv("DB_PORT", "5432"),
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

from datetime import timedelta

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    # "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    # "DEFAULT_AUTHENTICATION_CLASSES": [
    #     "rest_framework_simplejwt.authentication.JWTAuthentication",
    # ],
    "DEFAULT_AUTHENTICATION_CLASSES": ("api.authentication.LoggingJWTAuthentication",),
    "DEFAULT_THROTTLE_RATES": {
        "signin": "10/min",  # пример
    },
}

AUTHENTICATION_BACKENDS = [
    "api.authentication.EmailBackend",
    "django.contrib.auth.backends.ModelBackend",
]


SPECTACULAR_SETTINGS = {
    "TITLE": "MamaAir API",
    "DESCRIPTION": (
        "Backend API for the MamaAir mobile app. "
        "Use Google sign-in to obtain JWT Bearer tokens for protected endpoints. "
        "OpenAPI examples follow the mobile E2E flow in scripts/test_server_api.py."
    ),
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SCHEMA_PATH_PREFIX": r"/api/",
    "PREPROCESSING_HOOKS": ["api.schema_hooks.hide_non_mobile_endpoints"],
    "SWAGGER_UI_DIST": "SIDECAR",
    "SWAGGER_UI_FAVICON_HREF": "SIDECAR",
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=48),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=30),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "USER_ID_FIELD": "email",
    "USER_ID_CLAIM": "email",
}

# Static files (for nginx)
STATIC_URL = "/static/"
# STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATIC_ROOT = "/app/static"

MEDIA_URL = "/media/"
MEDIA_ROOT = "/app/media"


# Time zone, language, etc. can stay default or be adjusted
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} [{name}.{funcName}] - {message}",
            "style": "{",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
        "simple": {
            "format": "[{levelname}] {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",  # or "simple" if you want
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",  # can be DEBUG in dev
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "uvicorn": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "uvicorn.error": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "uvicorn.access": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "api": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}


logger = logging.getLogger(__name__)
logger.info("Logging initialized")

# http
# ! TODO: remove this for https
if DJANGO_ENV in {"production", "staging"}:
    SESSION_COOKIE_SECURE = True  # если HTTPS
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = False
    CSRF_TRUSTED_ORIGINS = ["https://app.mamaair.com"]
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
else:
    SESSION_COOKIE_SECURE = False  # если HTTP
    CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SAMESITE = "Lax"


LOGOUT_REDIRECT_URL = "/api/login/"

LOGIN_URL = "/api/login/"

INTERNAL_IPS = [
    # ...
    "127.0.0.1",
    # ...
]
