# Generated by Django 5.2.1 on 2025-09-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(max_length=128)),
                ('version', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('condition', models.TextField(help_text='Python expression, returns True/False against eval context.')),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('moderate', 'Moderate'), ('info', 'Info')], default='info', max_length=16)),
                ('category', models.CharField(choices=[('medical', 'Medical'), ('air_quality', 'Air Quality'), ('lifestyle', 'Lifestyle'), ('general', 'General')], default='general', max_length=32)),
                ('enabled', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=100, help_text='Lower number = higher priority.')),
                ('cooldown_hours', models.PositiveIntegerField(default=24)),
                ('ttl_hours', models.PositiveIntegerField(default=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'recommendation_rules',
                'ordering': ['priority', '-updated_at'],
                'indexes': [models.Index(fields=['enabled', 'priority'], name='recommendat_enabled_040b10_idx'), models.Index(fields=['category'], name='recommendat_categor_212236_idx')],
                'constraints': [models.UniqueConstraint(fields=('rule_id', 'version'), name='uniq_rule_id_version')],
            },
        ),
    ]
