# Generated by Django 5.2.1 on 2025-10-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_populate_recommendations_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='MamaAirMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveSmallIntegerField()),
                ('locale', models.CharField(default='en', max_length=10)),
                ('text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['week', 'locale', 'is_active'], name='recommendat_week_cf2620_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('week', 'locale'), name='unique_active_mamaair_week_locale')],
            },
        ),
    ]
