# Generated by Django 5.2.1 on 2025-10-17 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_populate_mamaair_messages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MamaAirMessage',
            new_name='MamaAirWeeklyMessage',
        ),
        migrations.RenameIndex(
            model_name='mamaairweeklymessage',
            new_name='recommendat_week_4370aa_idx',
            old_name='recommendat_week_cf2620_idx',
        ),
    ]
