# Generated by Django 5.2.1 on 2026-02-21 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0005_rename_mamaairmessage_mamaairweeklymessage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendationrule',
            old_name='message',
            new_name='alert',
        ),
        migrations.AddField(
            model_name='recommendationrule',
            name='recommendation_activity',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='recommendationrule',
            name='recommendation_behavior',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='recommendationrule',
            name='recommendation_diet',
            field=models.TextField(blank=True, default=''),
        ),
    ]
