# Generated by Django 5.2.1 on 2026-02-21 11:20

from django.db import migrations


def forwards(apps, schema_editor):
    RecommendationRule = apps.get_model("recommendations", "RecommendationRule")

    # Map: rule_id -> (diet, activity, behavior)
    MAP = {
        # --- Medical ---
        "alert.preeclampsia": (
            "Keep a standard prenatal diet; ensure you’re getting enough nutrients from food/supplements as advised.",
            "If you have high blood pressure or severe symptoms, follow your clinician’s advice and avoid strenuous exercise until you’ve been evaluated. Stay well-hydrated and avoid overheating.",
            "Because these can be warning signs of preeclampsia, contact your OB/GYN as soon as possible. If symptoms are severe, seek urgent care.",
        ),
        "alert.preterm_labor": (
            "Keep your usual prenatal diet (prenatal vitamin, iron/folate as prescribed) and stay well-hydrated.",
            "Don’t start bed rest on your own — consult your doctor first.",
            "Get urgent assessment now if you have contractions, bleeding, possible leaking of fluid, fever, or you’re unsure/worried.",
        ),
        "alert.gdm": (
            "Spread carbs through the day; pregnancy needs at least 175 g/day of carbohydrate overall. Consult your doctor to tailor portions and timing.",
            "Moderate exercise (aim ~150 min/week) helps glucose control; get a quick clinical check first, then continue regular, safe activity and stay hydrated.",
            "Schedule the diagnostic glucose test.",
        ),
        "alert.lbw": (
            "Aim for nutrient-dense, calorie-adequate meals/snacks with enough protein.",
            "Avoid heavy lifting/overexertion.",
            "If you notice reduced or changed fetal movements, seek assessment as soon as possible.",
        ),
        "alert.placental_abruption": (
            "Do not delay urgent care to eat or drink; follow hospital instructions once you’re being assessed.",
            "Stop what you’re doing and get medical help now. Don’t drive yourself; arrange emergency transport or go to the hospital/maternity unit.",
            "Call emergency services / go to hospital immediately for bleeding with pain, tenderness, or frequent contractions.",
        ),
        # --- Air quality ---
        "alert.pm25.daily": (
            "Maintain increased hydration.",
            "Reduce outdoor exertion on high-PM days; schedule activity when cleaner; prefer indoor light exercise.",
            "Create a clean-air room with HEPA; wear a fitted N95 if you must go outside; keep windows closed during peaks.",
        ),
        "alert.no2.daily": (
            "Keep your usual prenatal diet (prenatal vitamin, iron/folate as advised) and stay hydrated.",
            "Avoid high-traffic corridors and vigorous outdoor activity near roadways during peaks.",
            "Improve kitchen ventilation; prefer electric/induction over gas; use range hoods; avoid idling vehicles near home.",
        ),
        "alert.o3.8h": (
            "Hydrate well (especially in warm weather).",
            "Shift outdoor exercise to morning/evening; avoid vigorous activity during ozone peaks.",
            "Close windows during peak ozone hours; ventilate/cool your home when levels drop (often mornings/evenings).",
        ),
        "alert.so2.daily": (
            "Stay well-hydrated.",
            "Avoid outdoor exertion during SO₂ peaks, especially near industrial plumes or busy roads; reschedule walks/workouts for cleaner-air hours.",
            "Close windows/doors during episodes; use recirculation on AC. Limit indoor particle-creating activities (smoking, frying) during poor air.",
        ),
        # --- Lifestyle / profile ---
        "alert.sleep.low": (
            "Hydrate during the day; avoid large/heavy meals close to bedtime. Limit caffeine in the afternoon/evening.",
            "Get daytime light activity and build an evening wind-down. Finish vigorous exercise ≥3 hours before bedtime; keep a consistent wake time.",
            "Target ≥7 h/night; keep a regular schedule; dim screens/lights before bed; a 20–30 min nap is OK earlier in the day if very tired.",
        ),
        "alert.bmi.low": (
            "Have nutrient-rich meals and discuss your diet with your doctor.",
            "Light-to-moderate activity is okay; avoid excessive energy deficits; add rest as needed.",
            "Ask for a dietitian referral and keep regular weight checks to stay within recommended gain range.",
        ),
        "alert.bmi.high": (
            "Emphasize vegetables, lean proteins, high-fiber carbs; limit added sugars.",
            "Aim ≥150 min/week moderate activity.",
            "Set structured meals/snacks; sleep ≥7 h to support metabolic health.",
        ),
        "alert.exercise.low": (
            "Hydrate before/during/after activity; balanced meals to support moderate exercise.",
            "Build to 150 min/week (e.g., brisk walking, swimming); include pelvic-floor and light resistance work; avoid high-risk sports.",
            "Use timing around cleaner air/cooler hours; plan 30-min sessions 5 days/week.",
        ),
    }

    # Populate only if fields are still empty (safe re-run)
    qs = RecommendationRule.objects.filter(enabled=True)
    for rule in qs.iterator():
        tpl = MAP.get(rule.rule_id)
        if not tpl:
            continue

        diet, activity, behavior = tpl

        changed = False
        if not (rule.recommendation_diet or "").strip():
            rule.recommendation_diet = diet
            changed = True
        if not (rule.recommendation_activity or "").strip():
            rule.recommendation_activity = activity
            changed = True
        if not (rule.recommendation_behavior or "").strip():
            rule.recommendation_behavior = behavior
            changed = True

        if changed:
            rule.save(
                update_fields=[
                    "recommendation_diet",
                    "recommendation_activity",
                    "recommendation_behavior",
                ]
            )


def backwards(apps, schema_editor):
    RecommendationRule = apps.get_model("recommendations", "RecommendationRule")
    # Rollback strategy: clear fields (optional)
    RecommendationRule.objects.update(
        recommendation_diet="",
        recommendation_activity="",
        recommendation_behavior="",
    )


class Migration(migrations.Migration):
    dependencies = [
        # IMPORTANT: set to your latest migration in recommendations app
        ("recommendations", "0006_rename_message_recommendationrule_alert_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
